
language: node_js

node_js:
  - 8

script:
  - npm run build
  - npm run lint

before_deploy:
  - npm run build-examples
deploy:
  skip_cleanup: true
  provider: surge
  project: ./assets/
  domain: rx-component.surge.sh
